### ISSUE TITLE
footer public

### ISSUE THREAD

**Issue by maxime841** [maxime841/second-life-front#11]
- [x] bouton à propos de nous

- [x] bouton mentions légales

- [x] le copyryght

- [x] bouton facebook

- [x] bouton instagram
- [ ] faire page a propos de nous
- [ ] faire page contact
- [ ] faire page mentions legales

**Comment by j314h** [comment]
@maxime841 pour avancer sur cette issus il faut que je sache
- si le design est ok ? (taille, couleur, police, position des elements à l'interieur etc....,  fait la liste de comment tu veux les choses pour qu'on puisse cloturer)
- les text sont en anglais est ce normal ?

**Comment by maxime841** [comment]
tout le footer on le garde comme çà il suffit juste de réaliser les trois page contact a propos de nous et mentions legales

**Comment by j314h** [comment]
ok je clos on ouvrira une autre issus
