### ISSUE TITLE
page home vitrine

### ISSUE THREAD

**Issue by maxime841** [maxime841/second-life-front#12]
- [x]  header public
- [ ] image concerant le jeu second life
- [x] paragraphe descriptif du site
- [x] footer public

**Comment by maxime841** [comment]
Il reste à placer correctement les image dans les bon dossier et les afficher avec les import!! bug pour ma part d'import a voir

**Comment by j314h** [comment]
@maxime841 donne moi les images que je puisse tester et les mettre en place

**Comment by maxime841** [comment]
@j314h je viens de mettre un dossier asset dans src il y a les trois images dedans je vais push maintenant

**Comment by j314h** [comment]
ok nickel

**Comment by maxime841** [comment]
@j314h photo sont affichées dans la page hom

**Comment by j314h** [comment]
@maxime841 ok je clos
