### ISSUE TITLE
page club vitrine

### ISSUE THREAD

**Issue by maxime841** [maxime841/second-life-front#14]
- [x]  header public
- [ ] composant club
- [x] footer public

**Comment by maxime841** [comment]
Salut john j'ai changer mon fichier type club.type.ts et j'ai tjs mon probleme pour récuperer mes donnée du club dans le volet pourra tu voir ce que j'ai fais stp?

**Comment by maxime841** [comment]
C'est bon mes données je les recupère bien par contre j'ai un autre soucis dans mon volet j'ai mis en place un carousel pour faire defiler les photo de flyers et dans mon carousel je l'ai choisi avec des fleche directionnel pour le defilement de photo qui sont des balise <a> le soucis c'est que ca me fais un lien au lieu de faire le defilement de photo (gros bug) je vois ps de soluce pour le moment. je m'arrete pour ce soir je reprendrai demain et si tu as une soluce je suis preneur..

**Comment by maxime841** [comment]
salut @j314h j'ai toujours un soucis de fichier type pour typer le club je pense avoir compris certaine chose dans mon fichier j'ai coder ceci
`/**
 * type for all clubs
 */
export interface IClub {
  id?: number
  name?: string
  owner?: string
  presentation?: string
  picture?: IPictureClubFavori // ici je déclare ma clé picture qui représente un objet que tu peux retrouver dans IPictureClubFavori
  pictures?: IPicturesClub[] // ici je déclare pictures comme un tableau => IPictures[] => je retrouve pas mes infos je comprend pas
  parties?: IParties[] // ici idem que pictures j'ai meme tester en mettant [IParties] ou [IPicturesClub] pour celle du haut. marche pas?
  club?: IClub
}

/**
 * type for display picture favori of club
 */
export interface IPictureClubFavori {
  id?: number
  name?: string
  picture_url?: string
  favori?: boolean
  picturable_id?: number
  picturable_type?: string
}

/**
 * type for all picture of clubs
 */
 export interface IPicturesClub {
  id?: number
  name?: string
  picture_url?: string
  favori?: boolean
  picturable_id?: number
  picturable_type?: string
}

/**
 * type for all parties of clubs
 */
 export interface IParties {
  id?: number
  name?: string
  owner?: string
  date_party?: Date
  picture_favoris?: IPicturePartieFavori
  pictures?: IPicturesParties[] // ici idem que les autres 
}

 /**
   * type for display picture favori of parties
   */
  export interface IPicturePartieFavori {
    id?: number
    name?: string
    picture_url?: string
    favori?: boolean
    picturable_id?: number
    picturable_type?: string
  }

  /**
 * type for all picture of parties of club
 */
   export interface IPicturesParties {
    id?: number
    name?: string
    picture_url?: string
    favori?: boolean
    picturable_id?: number
    picturable_type?: string
  }

/**
 * type for response one club
 */
export interface IClubResponse {
  club: IClub
}

/**
 * type for response all clubs
 */
export interface IClubsResponse {
  clubs?: IClub[]
}
`

je sais pas ce que j'ai mal fait car dans mon console.log quand je fais un test de trouver mes info quand c'est un objet c'est ok ca marche mais pour un tableau ca marche plus je cherche je cherche je trouve pas bizare

**Comment by maxime841** [comment]
j'ai meme tester avec cette facon export interface IPicturesClub extend Array<IClub> marche pas

**Comment by j314h** [comment]
@maxime841 quand tu auras regler le bug tu pushera que je puisse pull ;-)

**Comment by maxime841** [comment]
@j314h c'est ahurissant l'erreur ca me dis pictures n'existe pas sur le type IParties[] alors qu'il y ai

**Comment by j314h** [comment]
> @j314h c'est ahurissant l'erreur ca me dis pictures n'existe pas sur le type IParties[] alors qu'il y ai

ok je vais guetter

**Comment by j314h** [comment]
@maxime841 c'est quoi que tu veux faire je sais plus ? afficher les image des party ?

**Comment by maxime841** [comment]
oui c'est ca

**Comment by j314h** [comment]
![Image](https://user-images.githubusercontent.com/61687824/194544622-e594e410-dbfa-48d1-bbc5-fcb5f8e37a5d.png)

mais là gros tu recommences nan ? tu appelle pictures sur parties mais parties c'est un tableau ?

**Comment by j314h** [comment]
ouai c'est ça c'est bien un tableau donc c'est comme hier , tu refait un . sur un tableau
il faut faire 

```js
club.parties.map(partie => partie.pictures.map(picture => .... ))
```

**Comment by maxime841** [comment]
ah ok car je me disai club.pictures j'aurai les image du club et non celle des parties ok merci

**Comment by j314h** [comment]
ben club.pictures oui tu auras les picture du club mais ta mis club.parties

**Comment by j314h** [comment]
@maxime841 liste ce qu'il reste à faire exactement car au dessus de cette issus il rest composant club mais sa veux rien dire on sait pas ce qu'il reste exactement

**Comment by maxime841** [comment]
##Debug

- [ ] seulement le premier carrousel de chaque Card club est fonctionnel
- [ ] lors d'un appuie sur le bouton en savoir plus les cards se décalent toutes vers le bas ou le haut
- [ ] lors d'un appuie sur les carrousels la page web se déplace en hauteur (problème peux être lier avec le bug des bouton en savoir plus) ??? a voir

##CSS

- [ ] réaliser le responsive design des page tablette et card (agrandir les cards)

**Comment by j314h** [comment]
yop je vais cloturer cette issus car si j'ai bien compris il reste plus que le carousel, 
donc le carousel je vais le finir ce soir  (j'ai tous changer le daisyui ne fonctionne pas bien je t'expliquerai) 
et comme le carousel à son issus cele ci ne sert à rien
