### ISSUE TITLE
page profil house vitrine

### ISSUE THREAD

**Issue by maxime841** [maxime841/second-life-front#15]
- [x]  header public
- [x] composant house
- [x] activer un volet deroulant lors de l'appuie bouton en savoir plus
- [x] inserer les caractéristique dans le volet de la maison avec les photos sauf le titre et la presentation qui sont deja dans la card house
- [x] footer public

**Comment by j314h** [comment]
@maxime841 je coche header et public
pour le footer on ce reportera à l'issus #11 
pour le header j'ouvre une issus car il y a un grave soucis de responsive
concernant la tache composant house
il faut que tu fasses une liste en detaillant ce que tu veux dedans , genre : les card, les btn, les lien, les fonctionnalité qui aura dedans
fait une liste qu'on puisse valider chaque etape apres

**Comment by maxime841** [comment]
@j314h il reste un petit bug lorsque l'on fais défiler la page pour appuyer sur un carrousel en milieu de page cela créer un petit saut de page

**Comment by j314h** [comment]
@maxime841 en attente de ta réponse à l'issus #37

**Comment by maxime841** [comment]
j'ai vu tes modification et ca me vas donc on va faire la meme chose pour les card houses
