### ISSUE TITLE
mise en place de la fonctionnalité carousel

### ISSUE THREAD

**Issue by maxime841** [maxime841/second-life-front#37]

**Comment by j314h** [comment]
pourquoi cette issus ^^

**Comment by maxime841** [comment]
@j314h j'ai fait un petit fichier pour concevoir le carrousel dans sa globalité
`Carrousel

=> -récupérer toutes les images des parties selon les clubs
=> -afficher une à une les image
=> -créer deux boutons droite gauche pour le défilement des photos

récupérer les images des club

=>appel api 

afficher l'image l'une après l'autre

=> déclarer une variable image de base en position 0
=> afficher l'image de base
=> lors de l'appuie bouton left => index de l'image de base – 1
=> lors de l'appuie bouton right =>l'index de l' image de base +1

créer deux boutons droit et gauche

=> fonction bouton droit
   - lors de l'appuie bouton droit => ajouter + 1 a l'index de l'image
   
=> fonction bouton gauche
  - lors de l'appuie bouton gauche => enlever - 1 à l'index de l'image
`

je sais pas si c'est complet voir si tu rajouterai ou modifierai quelque chose

**Comment by j314h** [comment]
> @j314h j'ai fait un petit fichier pour concevoir le carrousel dans sa globalité `Carrousel
> 
> => -récupérer toutes les images des parties selon les clubs => -afficher une à une les image => -créer deux boutons droite gauche pour le défilement des photos
> 
> récupérer les images des club
> 
> =>appel api
> 
> afficher l'image l'une après l'autre
> 
> => déclarer une variable image de base en position 0 => afficher l'image de base => lors de l'appuie bouton left => index de l'image de base – 1 => lors de l'appuie bouton right =>l'index de l' image de base +1
> 
> créer deux boutons droit et gauche
> 
> => fonction bouton droit
> 
> * lors de l'appuie bouton droit => ajouter + 1 a l'index de l'image
> 
> => fonction bouton gauche
> 
> * lors de l'appuie bouton gauche => enlever - 1 à l'index de l'image
>   `
> 
> je sais pas si c'est complet voir si tu rajouterai ou modifierai quelque chose

ouai c'est pas mal
encore une fois je ne peux pas te dire quoi que ce soit
c'est ta logic, si c'est moi qui le fais je le ferais pas comme ça
donc je ne serai pas objectif, mais en tous ouai sa a l'aire d'etre bien

le truc c'est que ta pris style de model, là encore c'est pas bien il faut ton propre style 
il faut que sa te parle à toi, parceque en gros dans ton issus page club t'aurais juste une case à cocher carrousselle
et pis dans ton vscode t'aurais un fichier text avec ta logique pour creer cette fonctionnalité, c'est personnelle et non partageable dans le sens où les autre ne comprendrais rien.

par contre il peux arriver qu'on taff ensemble sur une fonctionnalité et là du coup on ferai une issus et on en parlerais
je t'aide pas beaucoup mais en meme temps je peux pas mdrr.

carrousselle 30 min mon gros aller go go

**Comment by maxime841** [comment]
@j314h mes deux boutons du caroussel on l'air fonctionnel mais par contre les image ne switch pas peux tu voir stp dans le fichier btn-card dans molecule stp

**Comment by j314h** [comment]
> @j314h mes deux boutons du caroussel on l'air fonctionnel mais par contre les image ne switch pas peux tu voir stp dans le fichier btn-card dans molecule stp

je vais regarder mais j'attends que les seeder finisse sa prends du temps

**Comment by maxime841** [comment]
j'ai mis des commentaires après avant que je parte

**Comment by maxime841** [comment]
j'ai pas copier coller j'ai vu que lorsque j'appuie sur mon bouton droit dans mon log j'avais des valeur negative donc j'ai créer un modulo pour avoir tjs des valeur positive

**Comment by j314h** [comment]
alors je comprends rien au code, si toi tu comprends c'est good mais franchement .... je plane à 10 000 mdrrr
du coup je peux pas t'aider
je peux te donner ce que moi j'aurais fait meme si sa te sert a rien peut etre tu pourra adapter je pas ...

- moi j'aurais pas fait un map sur les pictures j'aurais fait ça dans le html party.pictures[0] et le zero sa aurais été un compteur
et genre mes button font augmenter ou descendre ce compteur et j'aurais mis une limite basse de 0 et une limite haute du length du tableau, plus facile simple rapide ...

**Comment by j314h** [comment]
@maxime841 du coup pour pouvoir essayer de finir dans les temps du milestone
je mis en place le carousselle exactement comme sur le daisyui vu que tu l'avais pris avec ça
j'ai utiliser le fonctionnement de daisyui. ce n'est pas finis et j'ai fais une mise en page grossiere
donc y a encore du taff, surtout dimmention le carrousselle et faire pour que les image se mete bien dans le carde
du coup faudra que tu pull je sais pas si t'aura des conflit mais fait attention au cas où de pas tout péter mdrrr
aller à plus

**Comment by j314h** [comment]
je fais une liste de ce qui reste à faire pour moi sur cette issus à completer

- [ ] design de la taille du carousselle
- [ ] design de la présentation des party (title, date etc ...., voir peut etre pour mettre un divisor entre chaque party)

**Comment by maxime841** [comment]
salut @j314h bon je vois que tu as tafer sur le carousel je vais pull ton code et continuer cet apres midi et des que c'est fini le css je close l'issue et je te prendrai l'issue page profil house vitrine

**Comment by j314h** [comment]
> salut @j314h bon je vois que tu as tafer sur le carousel je vais pull ton code et continuer cet apres midi et des que c'est fini le css je close l'issue et je te prendrai l'issue page profil house vitrine

alors je serai pas dispo en début d'aprem
du coup j'ai fait des test à midi, les différents carrousselle sont en conflit au niveau des click et c'est normal les href et les id doive etre unique par party du coup il faudra rajouter le id de la party en plus de l'index dans les id et href

**Comment by j314h** [comment]
@maxime841 yop, j'ai finis le carousel pour le club, du coup je t'explique, j'ai de oufffff galererrrrrrrrrrrrr
car vu que aucun design n'est fait j'ai eu beaucoup de mal d'imaginé ce que tu voulais j'ai perdu un temps fou
donc j'ai refais toute la page club, à cause de trois choses

- le choix de disposition en affichant des cards l'une à coté de l'autre est un mauvais choix visuel, car par exemple si tu as 2 card l'une à coté de l'autre, si tu clique pour ouvrir le volet de une card forcement l'autre à coté s'agrandi aussi mais elle ne contiendra aucune info c'est logic mais le visuel pas top du tout

- le responsive était horible et inadéquate.....

- j'ai l'impression qu'il manquais plein d'info pour le club ou les partie (je connais pas trop le projet donc j'ai essayer d'imaginé)

du coup voila à cause de ses trois chose j'ai décider de tout refaire ET DONC la partie land n'est pas faite, car j'atttends d'avoir ton feux vert ton approbation que la parti club te conviens et donc dans ce cas je ferai la partie land

alors pour demain tu pull tu test la page club et tu me dis, en attendant que je fasse la partie land (cette fois sa ira tres vite genre 30 min) tu pourras faire le responsive du headerdonc normalement vers 15h (vu qu'on commence pas avant 13h mdrrr) on aura finis le milestone qui etait prévue dimanche, donc apres on enchaine vite pour rattrapper le retard, voila mon gros. à demain

PS : je clos cette issus répond dans l'issus de house
