### ISSUE TITLE
responsive header

### ISSUE THREAD

**Issue by j314h** [maxime841/second-life-front#38]
- [ ] voir reglage responsive

**Comment by maxime841** [comment]
@j314h normalement le header est ok même responsive tu as vu des choses qui n'allais pas?

**Comment by j314h** [comment]
le responsive ne va pas du tout, la barre de recherche par exemple touche un btn du menu
tous est compresser et pis en mobile sa me fait une barre de défillement de gauche à droite je sais pas si c'est du au header mais on dirais bien

**Comment by j314h** [comment]
@maxime841 du je l'ai fais , et je rajoute une issus car il y a un soucis avec les images de la page home en mode mobile elle sont inline au lieux d'etre en column. 

j'ai du enlever la barre de recherche dans le header en mode mobile donc il faudra la rajouter en haut de la page home. donc je met également cette tache dans l'issus.

je clos celle ci elle est finis
