### ISSUE TITLE
page forgot password + send email reset password

### ISSUE THREAD

**Issue by j314h** [maxime841/second-life-front#9]
- [x] page mot de passe oublié
- [x] formulaire envoie mail pour reset mot de passe
- [ ] page reset mot de passe

**Comment by j314h** [comment]
@maxime841 dans le compte github console_log il y a un repo .env , je vais mettre dedans le .env car je l'ai modifié, tu copieras le code pour mettre le tiens à jour je le fais dans 5 min

**Comment by maxime841** [comment]
@j314h ok ca marche

**Comment by j314h** [comment]
@maxime841 attention au info de la database dans le .env on a pas les meme

**Comment by maxime841** [comment]
j'ai copier coller ton .env j'ai remis ma bonne database et mon user et password j'ai rien a push bizare

**Comment by j314h** [comment]
.env pas dans git

**Comment by j314h** [comment]
OH MY GOD, c'est normal que tu ai rien à push le .env est jamais dans le github interdit ta oublié ?????

**Comment by maxime841** [comment]
ah mais j'ai pris celui ou tu as pas fait la modif je vois tu as rajouter encore une ligne

**Comment by j314h** [comment]
ouai j'avais oublié une ligne
mais meme si tu mets celle la sa change rien t'aura rien à push
les .env ne vont pas sur github, c'est pour sa que j'ai creer un repo private que seulement toi et moi on vois pour récupe les info sensible ;-)

**Comment by maxime841** [comment]
oui oui j'ai compris mon anerie on le met dans le gitignore
